# Generated by Django 4.2.5 on 2026-01-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualLabSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment_name", models.CharField(max_length=200)),
                ("v1_observed", models.FloatField()),
                ("v2_observed", models.FloatField()),
                ("calc_na2co3", models.FloatField()),
                ("calc_nahco3", models.FloatField()),
                ("total_score", models.IntegerField()),
                ("penalty_log", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.student",
                    ),
                ),
            ],
        ),
    ]
