# Generated by Django 4.2.5 on 2026-03-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0003_labexperiment_experimenttargetconfig_experimentstep_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparatusCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        help_text="e.g., volumetric_flask, beaker, burette",
                        max_length=50,
                    ),
                ),
                ("max_capacity", models.FloatField(help_text="In mL")),
                (
                    "svg_sprite_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_heatable", models.BooleanField(default=False)),
                ("can_measure_vol", models.BooleanField(default=False)),
                ("can_pour", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("formula", models.CharField(max_length=100)),
                (
                    "molarity",
                    models.FloatField(
                        blank=True,
                        help_text="Default molarity if applicable",
                        null=True,
                    ),
                ),
                ("density", models.FloatField(default=1.0, help_text="g/mL")),
                (
                    "default_color_hex",
                    models.CharField(
                        default="#FFFFFF80", help_text="Format: #RRGGBBAA", max_length=9
                    ),
                ),
                ("is_indicator", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MilestoneRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_vessel",
                    models.CharField(
                        help_text="e.g., 'conical_flask' or apparatus ID",
                        max_length=100,
                    ),
                ),
                (
                    "target_property",
                    models.CharField(
                        help_text="e.g., 'hcl_vol', 'temperature', 'ph'", max_length=100
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", "Greater Than"),
                            (">=", "Greater Than or Equal"),
                            ("<", "Less Than"),
                            ("<=", "Less Than or Equal"),
                            ("==", "Equal To"),
                            ("!=", "Not Equal To"),
                            ("CONTAINS", "Contains Object"),
                        ],
                        default=">=",
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField(help_text="Target threshold value")),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="main_app.experimentmilestone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_color_hex",
                    models.CharField(default="#FFFFFF80", max_length=9),
                ),
                ("ph_change", models.FloatField(default=0.0)),
                (
                    "chemical_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions_as_a",
                        to="main_app.chemicalcatalog",
                    ),
                ),
                (
                    "chemical_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions_as_b",
                        to="main_app.chemicalcatalog",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions_as_product",
                        to="main_app.chemicalcatalog",
                    ),
                ),
            ],
        ),
    ]
