# Generated by Django 4.2.5 on 2026-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_apparatuscatalog_chemicalcatalog_milestonerule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmilestone",
            name="instruction",
            field=models.TextField(
                blank=True,
                help_text="Shown in the Lab Assistant panel as guidance to the student for completing this step.",
                null=True,
            ),
        ),
    ]
