# Generated by Django 4.2.5 on 2026-03-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_experimentmilestone_instruction"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "pass_percentage",
                    models.FloatField(
                        default=60.0, help_text="Minimum Quiz % to unlock lab"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.labexperiment",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.quiz",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="main_app.subject",
                    ),
                ),
                (
                    "video_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.videocourse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_watched", models.BooleanField(default=False)),
                ("quiz_passed", models.BooleanField(default=False)),
                ("latest_quiz_score", models.FloatField(default=0.0)),
                ("lab_completed", models.BooleanField(default=False)),
                ("lab_score", models.FloatField(default=0.0)),
                ("overall_grade", models.FloatField(default=0.0)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "lesson_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="main_app.lessonmodule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="main_app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "lesson_module")},
            },
        ),
    ]
