# Generated by Django 4.2.5 on 2026-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_lessonmodule_studentprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="labexperiment",
            name="initial_state_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Scene items (apparatus, locations, optional contents) for the simulation.",
            ),
        ),
    ]
