# Generated by Django 4.2.5 on 2026-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_lessonmodule_studentprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g., 'v1_reading'", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="e.g., 'Enter the endpoint (V1) reading in mL:'"
                    ),
                ),
                (
                    "target_vessel",
                    models.CharField(
                        default="burette",
                        help_text="Vessel to check against",
                        max_length=100,
                    ),
                ),
                (
                    "target_property",
                    models.CharField(
                        default="reading",
                        help_text="Property to check (e.g. 'reading', 'volume')",
                        max_length=100,
                    ),
                ),
                (
                    "tolerance",
                    models.FloatField(
                        default=0.2, help_text="Margin of error allowed for students"
                    ),
                ),
                ("penalty_points", models.IntegerField(default=10)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_prompts",
                        to="main_app.experimentmilestone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculationPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g., 'mass_na2co3'", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Math problem instructions for the student."
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        help_text="e.g., '(v1_reading * 0.1 * 106) / 1000'. Extracted variables must match Observation titles.",
                        max_length=255,
                    ),
                ),
                (
                    "tolerance",
                    models.FloatField(default=0.05, help_text="Allowed math variance"),
                ),
                ("points", models.IntegerField(default=15)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_prompts",
                        to="main_app.experimentmilestone",
                    ),
                ),
            ],
        ),
    ]
