# Generated by Django 4.2.5 on 2026-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_observationprompt_calculationprompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtuallabsubmission",
            name="calc_na2co3",
        ),
        migrations.RemoveField(
            model_name="virtuallabsubmission",
            name="calc_nahco3",
        ),
        migrations.RemoveField(
            model_name="virtuallabsubmission",
            name="v1_observed",
        ),
        migrations.RemoveField(
            model_name="virtuallabsubmission",
            name="v2_observed",
        ),
        migrations.AddField(
            model_name="virtuallabsubmission",
            name="calculations",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="virtuallabsubmission",
            name="observations",
            field=models.JSONField(default=dict),
        ),
    ]
