# Generated by Django 4.2.5 on 2026-04-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_labexperiment_initial_state_json"),
        ("main_app", "0008_remove_virtuallabsubmission_calc_na2co3_and_more"),
    ]

    operations = []
