# Generated by Django 4.2.5 on 2026-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_merge_20260404_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalcatalog",
            name="high_ph_color",
            field=models.CharField(
                default="#FF00FFA0",
                help_text="#RRGGBBAA for basic color (e.g. Pink for Phenolphthalein)",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="chemicalcatalog",
            name="low_ph_color",
            field=models.CharField(
                default="#FFFF00A0",
                help_text="#RRGGBBAA for acidic color (e.g. Yellow for Methyl Orange)",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="chemicalcatalog",
            name="transition_ph_range",
            field=models.CharField(
                default="8.2-10.0",
                help_text="Lower and Upper pH bound, e.g. '8.2-10.0'",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="experimenttargetconfig",
            name="v1_color",
            field=models.CharField(
                default="#FF69B4A0", help_text="Flask color at V1", max_length=9
            ),
        ),
        migrations.AddField(
            model_name="experimenttargetconfig",
            name="v2_color",
            field=models.CharField(
                default="#FFD700B4", help_text="Flask color at V2", max_length=9
            ),
        ),
    ]
