# Generated by Django 4.2.5 on 2026-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_chemicalcatalog_high_ph_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmilestone",
            name="is_manual",
            field=models.BooleanField(
                default=False,
                help_text="If true, student must manually click 'Record' to finish this step.",
            ),
        ),
    ]
