# Generated by Django 4.2.5 on 2026-04-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_experimentmilestone_is_manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentmilestone",
            name="is_manual",
        ),
    ]
