# Generated by Django 4.2.5 on 2026-04-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_remove_experimentmilestone_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmilestone",
            name="linked_reaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.chemicalreaction",
            ),
        ),
    ]
